"""repo-details-and-flow-incolumns

Revision ID: 0a5f21557119
Revises: 1defbd72658b
Create Date: 2026-04-01 16:38:09.803591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a5f21557119'
down_revision: Union[str, Sequence[str], None] = '1defbd72658b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow_states', sa.Column('repo_owner', sa.String(length=64), server_default='', nullable=False))
    op.add_column('flow_states', sa.Column('repo_name', sa.String(length=64), server_default='', nullable=False))
    op.add_column('flow_states', sa.Column('flow_name', sa.String(length=64), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flow_states', 'flow_name')
    op.drop_column('flow_states', 'repo_name')
    op.drop_column('flow_states', 'repo_owner')
    # ### end Alembic commands ###
