"""initial

Revision ID: 1defbd72658b
Revises:
Create Date: 2026-04-01 15:58:49.824950

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from persistence.postgres import JSONType

# revision identifiers, used by Alembic.
revision: str = "1defbd72658b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flow_states",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("flow_uuid", sa.String(length=255), nullable=False),
        sa.Column("method_name", sa.String(length=255), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state_json", JSONType(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_flow_states_uuid", "flow_states", ["flow_uuid"], unique=False)
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("issue_number", sa.Integer(), nullable=False),
        sa.Column("payment_id", sa.String(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("payment_method", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("verified_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pending_feedback",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("flow_uuid", sa.String(length=255), nullable=False),
        sa.Column("context_json", JSONType(), nullable=False),
        sa.Column("state_json", JSONType(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("flow_uuid"),
    )
    op.create_index("idx_pending_feedback_uuid", "pending_feedback", ["flow_uuid"], unique=False)
    op.create_table(
        "requests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("issue_number", sa.Integer(), nullable=False),
        sa.Column("request_text", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("commit", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("requests")
    op.drop_index("idx_pending_feedback_uuid", table_name="pending_feedback")
    op.drop_table("pending_feedback")
    op.drop_table("payments")
    op.drop_index("idx_flow_states_uuid", table_name="flow_states")
    op.drop_table("flow_states")
    # ### end Alembic commands ###
