---
name: Update Deployment

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      stack:
        required: true
        type: string
      env:
        required: true
        type: string
      version_name:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  up:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          repository: tributary-so/deployment
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Setup Python ✨
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - uses: snok/install-poetry@v1
        with:
          version: 1.8.2
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Installing dependencies 📦️
        working-directory: ${{ inputs.path }}
        run: poetry install --no-interaction --no-root

      - name: Install pulumi 💾
        uses: pulumi/actions@v4

      - name: Save new image version to ESC ⭐
        run: |
          pulumi org set-default polycode
          pulumi env set ${{ inputs.env }} ${{inputs.version_name}} ${{ inputs.version }}
        working-directory: ${{ inputs.path }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Applying infrastructure 🚀
        uses: pulumi/actions@v4
        with:
          command: up
          work-dir: ${{ inputs.path }}
          stack-name: "${{ inputs.stack }}"
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
