name: Build and Deploy Landingpage

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: apps/landing

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: apps/landing/pnpm-lock.yaml

      - name: Build App
        run: pnpm run build
        env:
          VITE_N8N_WEBHOOK_URL: https://n8n.chainsquad.com/webhook/b95ac3dc-efd0-4acf-b0e8-1c554d341cf1

      - name: Deploy to external repository
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/landing/dist
          cname: polycod.ing
