---
name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev
        working-directory: apps/polycode/

      - name: setup git
        run: |
          git config --global user.email "polycode@polycod.ing"
          git config --global user.name "Polycode pipeline"

      - name: Run pytest
        run: uv run pytest
        env:
          GITHUB_TOKEN: xxx
        working-directory: apps/polycode/

      - name: Run pyright
        run: uv run pyright
        working-directory: apps/polycode/
